#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
# https://google.github.io/accompanist/
[versions]
accompanist = "0.31.5-beta"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-testharness = { module = "com.google.accompanist:accompanist-testharness", version.ref = "accompanist" }
accompanist-themeadapter-appcompat = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version.ref = "accompanist" }
accompanist-themeadapter-core = { module = "com.google.accompanist:accompanist-themeadapter-core", version.ref = "accompanist" }
accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

[bundles]
accompanist = [
    "accompanist-adaptive",
    "accompanist-drawablepainter",
    "accompanist-navigation-material",
    "accompanist-permissions",
    "accompanist-placeholder-material",
    "accompanist-systemuicontroller",
    "accompanist-testharness",
    "accompanist-themeadapter-appcompat",
    "accompanist-themeadapter-core",
    "accompanist-themeadapter-material3",
    "accompanist-webview",
]
