#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
activity = "1.8.0-alpha06"
ads = "1.0.0-alpha05"
annotation = "1.7.0-alpha02"
appcompat = "1.7.0-alpha02"
appsearch = "1.1.0-alpha03"
arch-core = "2.2.0"
asynclayoutinflater = "1.0.0"
autofill = "1.3.0-alpha01"
biometric = "1.2.0-alpha05"
browser = "1.6.0-beta01"
cardview = "1.0.0"
collection = "1.3.0-alpha04"
concurrent = "1.2.0-alpha01"
constraintlayout = "2.2.0-alpha10"
contentpager = "1.0.0"
coordinatorlayout = "1.2.0"
core-uwb = "1.0.0-alpha05"
credentials = "1.2.0-alpha05"
cursoradapter = "1.0.0"
customview = "1.2.0-alpha02"
customview-poolingcontainer = "1.0.0"

[libraries]
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
ads = { module = "androidx.ads:ads-identifier", version.ref = "ads" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
appsearch = { module = "androidx.appsearch:appsearch", version.ref = "appsearch" }
appsearch-local-storage = { module = "androidx.appsearch:appsearch-local-storage", version.ref = "appsearch" }
appsearch-platform-storage = { module = "androidx.appsearch:appsearch-platform-storage", version.ref = "appsearch" }
arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "arch-core" }
arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "arch-core" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core" }
asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "asynclayoutinflater" }
autofill = { module = "androidx.autofill:autofill", version.ref = "autofill" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
collection = { module = "androidx.collection:collection", version.ref = "collection" }
collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collection" }
concurrent = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent" }
concurrent-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
contentpager = { module = "androidx.contentpager:contentpager", version.ref = "contentpager" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core-uwb = { module = "androidx.core.uwb:uwb", version.ref = "core-uwb" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
cursoradapter = { module = "androidx.cursoradapter:cursoradapter", version.ref = "cursoradapter" }
customview = { module = "androidx.customview:customview", version.ref = "customview" }
customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" }

[bundles]
androidx = [
    "activity",
    "ads",
    "annotation",
    "appcompat",
    "appcompat-resources",
    "appsearch",
    "appsearch-local-storage",
    "appsearch-platform-storage",
    "arch-core-common",
    "arch-core-runtime",
    "arch-core-testing",
    "asynclayoutinflater",
    "autofill",
    "biometric",
    "biometric-ktx",
    "browser",
    "cardview",
    "collection",
    "collection-ktx",
    "concurrent",
    "concurrent-ktx",
    "constraintlayout",
    "contentpager",
    "coordinatorlayout",
    "core-uwb",
    "credentials",
    "credentials-play-services-auth",
    "cursoradapter",
    "customview",
    "customview-poolingcontainer",
    "constraintlayout",
    "constraintlayout",
]
