#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
activity = "1.8.0-alpha06"
ads = "1.0.0-alpha05"
annotation = "1.7.0-alpha02"
appcompat = "1.7.0-alpha02"
appsearch = "1.1.0-alpha03"
arch-core = "2.2.0"
asynclayoutinflater = "1.0.0"
autofill = "1.3.0-alpha01"
biometric = "1.2.0-alpha05"

[libraries]
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
ads = { module = "androidx.ads:ads-identifier", version.ref = "ads" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
appsearch = { module = "androidx.appsearch:appsearch", version.ref = "appsearch" }
appsearch-local-storage = { module = "androidx.appsearch:appsearch-local-storage", version.ref = "appsearch" }
appsearch-platform-storage = { module = "androidx.appsearch:appsearch-platform-storage", version.ref = "appsearch" }
arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "arch-core" }
arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "arch-core" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core" }
asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "asynclayoutinflater" }
autofill = { module = "androidx.autofill:autofill", version.ref = "autofill" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }

[bundles]
androidx = [
    "activity",
    "ads",
    "annotation",
    "appcompat",
    "appcompat-resources",
    "appsearch",
    "appsearch-local-storage",
    "appsearch-platform-storage",
    "arch-core-common",
    "arch-core-runtime",
    "arch-core-testing",
    "asynclayoutinflater",
    "autofill",
    "biometric",
    "biometric-ktx",
]
