#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
activity = "1.8.0-alpha06"
ads = "1.0.0-alpha05"
annotation = "1.7.0-alpha02"
appcompat = "1.7.0-alpha02"
appsearch = "1.1.0-alpha03"
arch-core = "2.2.0"
asynclayoutinflater = "1.0.0"
autofill = "1.3.0-alpha01"
biometric = "1.2.0-alpha05"
browser = "1.6.0-beta01"
cardview = "1.0.0"
collection = "1.3.0-alpha04"
concurrent = "1.2.0-alpha01"
constraintlayout = "2.2.0-alpha10"
contentpager = "1.0.0"
coordinatorlayout = "1.2.0"
core = "1.12.0-alpha05"
core-animation = "1.0.0-beta01"
core-google-shortcuts = "1.1.0"
core-performance = "1.0.0-alpha02"
core-remoteviews = "1.0.0-beta04"
core-role = "1.1.0-rc01"
core-splashscreen = "1.1.0-alpha01"
core-telecom = "1.0.0-alpha01"
core-uwb = "1.0.0-alpha05"
credentials = "1.2.0-alpha05"
cursoradapter = "1.0.0"
customview = "1.2.0-alpha02"
customview-poolingcontainer = "1.0.0"
documentfile = "1.1.0-alpha01"
draganddrop = "1.0.0"
drawerlayout = "1.2.0"
dynamicanimation = "1.1.0-alpha03"
emoji = "1.2.0-alpha03"
emoji2 = "1.4.0-beta05"
emojipicker = "1.0.0-alpha03"
enterprise = "1.1.0"
exifinterface = "1.3.6"
fragment = "1.7.0-alpha01"
graphics-core = "1.0.0-alpha04"
graphics-path = "1.0.0-alpha02"
graphics-shapes = "1.0.0-alpha03"
gridlayout = "1.1.0-beta01"
health = "1.0.0-beta03"
health-connect = "1.1.0-alpha02"
heifwriter = "1.1.0-alpha01"
input = "1.0.0-beta01"
interpolator = "1.0.0"
javascriptengine = "1.0.0-alpha05"

[libraries]
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
ads = { module = "androidx.ads:ads-identifier", version.ref = "ads" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
appsearch = { module = "androidx.appsearch:appsearch", version.ref = "appsearch" }
appsearch-local-storage = { module = "androidx.appsearch:appsearch-local-storage", version.ref = "appsearch" }
appsearch-platform-storage = { module = "androidx.appsearch:appsearch-platform-storage", version.ref = "appsearch" }
arch-core-common = { module = "androidx.arch.core:core-common", version.ref = "arch-core" }
arch-core-runtime = { module = "androidx.arch.core:core-runtime", version.ref = "arch-core" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch-core" }
asynclayoutinflater = { module = "androidx.asynclayoutinflater:asynclayoutinflater", version.ref = "asynclayoutinflater" }
autofill = { module = "androidx.autofill:autofill", version.ref = "autofill" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "biometric" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
collection = { module = "androidx.collection:collection", version.ref = "collection" }
collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collection" }
concurrent = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrent" }
concurrent-ktx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
contentpager = { module = "androidx.contentpager:contentpager", version.ref = "contentpager" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core = { module = "androidx.core:core", version.ref = "core" }
core-animation = { module = "androidx.core:core-animation", version.ref = "core-animation" }
core-animation-testing = { module = "androidx.core:core-animation-testing", version.ref = "core-animation" }
core-google-shortcuts = { module = "androidx.core:core-google-shortcuts", version.ref = "core-google-shortcuts" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
core-performance = { module = "androidx.core:core-performance", version.ref = "core-performance" }
core-remoteviews = { module = "androidx.core:core-remoteviews", version.ref = "core-remoteviews" }
core-role = { module = "androidx.core:core-role", version.ref = "core-role" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
core-telecom = { module = "androidx.core:core-telecom", version.ref = "core-telecom" }
core-uwb = { module = "androidx.core.uwb:uwb", version.ref = "core-uwb" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
cursoradapter = { module = "androidx.cursoradapter:cursoradapter", version.ref = "cursoradapter" }
customview = { module = "androidx.customview:customview", version.ref = "customview" }
customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customview-poolingcontainer" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
draganddrop = { module = "androidx.draganddrop:draganddrop", version.ref = "draganddrop" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
dynamicanimation-ktx = { module = "androidx.dynamicanimation:dynamicanimation-ktx", version.ref = "dynamicanimation" }
emoji-appcompat = { module = "androidx.emoji:emoji-appcompat", version.ref = "emoji" }
emoji-bundled = { module = "androidx.emoji:emoji-bundled", version.ref = "emoji" }
emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2" }
emoji2-bundled = { module = "androidx.emoji2:emoji2-bundled", version.ref = "emoji2" }
emoji2-picker = { module = "androidx.emoji2:emojipicker", version.ref = "emojipicker" }
emoji2-views = { module = "androidx.emoji2:emoji2-views", version.ref = "emoji2" }
emoji2-views-helper = { module = "androidx.emoji2:emoji2-views-helper", version.ref = "emoji2" }
enterprise = { module = "androidx.enterprise:enterprise-feedback", version.ref = "enterprise" }
enterprise-testing = { module = "androidx.enterprise:enterprise-feedback-testing", version.ref = "enterprise" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragment" }
graphics-core = { module = "androidx.graphics:graphics-core", version.ref = "graphics-core" }
graphics-path = { module = "androidx.graphics:graphics-path", version.ref = "graphics-path" }
graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "graphics-shapes" }
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
health = { module = "androidx.health:health-services-client", version.ref = "health" }
health-connect = { module = "androidx.health.connect:connect-client", version.ref = "health-connect" }
heifwriter = { module = "androidx.heifwriter:heifwriter", version.ref = "heifwriter" }
input = { module = "androidx.input:input-motionprediction", version.ref = "input" }
interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }
javascriptengine = { module = "androidx.javascriptengine:javascriptengine", version.ref = "javascriptengine" }

[bundles]
androidx = [
    "activity",
    "ads",
    "annotation",
    "appcompat",
    "appcompat-resources",
    "appsearch",
    "appsearch-local-storage",
    "appsearch-platform-storage",
    "arch-core-common",
    "arch-core-runtime",
    "arch-core-testing",
    "asynclayoutinflater",
    "autofill",
    "biometric",
    "biometric-ktx",
    "browser",
    "cardview",
    "collection",
    "collection-ktx",
    "concurrent",
    "concurrent-ktx",
    "constraintlayout",
    "contentpager",
    "coordinatorlayout",
    "core",
    "core-animation",
    "core-google-shortcuts",
    "core-ktx",
    "core-performance",
    "core-remoteviews",
    "core-role",
    "core-splashscreen",
    "core-telecom",
    "core-uwb",
    "credentials",
    "credentials-play-services-auth",
    "cursoradapter",
    "customview",
    "customview-poolingcontainer",
    "documentfile",
    "drawerlayout",
    "dynamicanimation",
    "dynamicanimation-ktx",
    "dynamicanimation-ktx",
    "emoji-appcompat",
    "emoji-bundled",
    "emoji2",
    "emoji2-bundled",
    "emoji2-picker",
    "emoji2-views",
    "emoji2-views-helper",
    "enterprise",
    "enterprise-testing",
    "exifinterface",
    "fragment",
    "fragment-ktx",
    "graphics-core",
    "graphics-path",
    "graphics-shapes",
    "gridlayout",
    "health",
    "health-connect",
    "heifwriter",
    "input",
    "interpolator",
    "javascriptengine",
]
androidTesting = [
    "core-animation-testing"
]
debugImplementation = [
    "fragment-testing"
]

