#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
coil = "2.4.0"

[libraries]
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

[bundles]
coil = [
    "coil",
    "coil-compose",
    "coil-gif",
    "coil-svg",
    "coil-video"
]
