#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
room = "2.6.0-alpha02"
sqlite = "2.4.0-alpha02"
sqlcipher = "4.5.4"

[libraries]
room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-rxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }
room-rxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
room-guava = { module = "androidx.room:room-guava", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }
sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }

[bundles]
sqlite = [
    "sqlcipher",
    "sqlite",
    "sqlite-ktx",
    "sqlite-framework",
]
room = [
    "room",
    "room-ktx",
    "room-rxjava2",
    "room-rxjava3",
    "room-guava",
    "room-paging",
]
kapt = [
    "room-compiler",
]
ksp = [
    "room-compiler",
]
annotationProcessor = [
    "room-compiler",
]
testImplementation = [
    "room-testing",
]