#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
tracing = "1.3.0-alpha02"

[libraries]
tracing = { module = "androidx.tracing:tracing", version.ref = "tracing" }
tracing-ktx = { module = "androidx.tracing:tracing-ktx", version.ref = "tracing" }

[bundles]
debug = [
    "tracing",
    "tracing-ktx",
]
