#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
# Third-party Libraries.
[versions]
accompanist = "0.31.5-beta"
coil = "2.4.0"
easydeviceinfo = "2.4.1" # https://github.com/nisrulz/easydeviceinfo
moshi = "1.15.0"
moshi-adapters = "1.15.0"
moshi-kotlin = "1.15.0"
moshi-kotlin-codegen = "1.15.0"
moshi-geojson = "1.0"
moshipack = "1.0.1"
moshipack-retrofit = "1.0.1"
retrofit = "2.9.0" # https://github.com/square/retrofit
retrofit2-kotlinx-serialization-converter = "1.0.0"
sqlcipher = "4.5.4"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-testharness = { module = "com.google.accompanist:accompanist-testharness", version.ref = "accompanist" }
accompanist-themeadapter-appcompat = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version.ref = "accompanist" }
accompanist-themeadapter-core = { module = "com.google.accompanist:accompanist-themeadapter-core", version.ref = "accompanist" }
accompanist-themeadapter-material3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }
easydeviceinfo = { module = "com.github.nisrulz:easydeviceinfo", version.ref = "easydeviceinfo" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi-adapters" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen" }
moshi-geojson = { module = "dev.haeusler.geojson-kotlin:geojson-moshi", version.ref = "moshi-geojson" }
moshipack = { module = "com.daveanthonythomas.moshipack:moshipack", version.ref = "moshipack" }
moshipack-retrofit = { module = "com.daveanthonythomas.moshipack:moshipack-retrofit", version.ref = "moshipack-retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-guava = { module = "com.squareup.retrofit2:adapter-guava", version.ref = "retrofit" }
retrofit-adapter-java8 = { module = "com.squareup.retrofit2:adapter-java8", version.ref = "retrofit" }
retrofit-adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
retrofit-adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
retrofit-adapter-scala = { module = "com.squareup.retrofit2:adapter-scala", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-guava = { module = "com.squareup.retrofit2:converter-guava", version.ref = "retrofit" }
retrofit-converter-jackson = { module = "com.squareup.retrofit2:converter-jackson", version.ref = "retrofit" }
retrofit-converter-java8 = { module = "com.squareup.retrofit2:converter-java8", version.ref = "retrofit" }
retrofit-converter-jaxb = { module = "com.squareup.retrofit2:converter-jaxb", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-converter-protobuf = { module = "com.squareup.retrofit2:converter-protobuf", version.ref = "retrofit" }
retrofit-converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit-converter-simplexml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit" }
retrofit-converter-wire = { module = "com.squareup.retrofit2:converter-wire", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }

[bundles]
accompanist = [
    "accompanist-adaptive",
    "accompanist-drawablepainter",
    "accompanist-navigation-material",
    "accompanist-permissions",
    "accompanist-placeholder-material",
    "accompanist-systemuicontroller",
    "accompanist-testharness",
    "accompanist-themeadapter-appcompat",
    "accompanist-themeadapter-core",
    "accompanist-themeadapter-material3",
    "accompanist-webview",
]
coil = [
    "coil",
    "coil-compose",
    "coil-gif",
    "coil-svg",
    "coil-video"
]
database = [
    "sqlcipher",
]
moshi = [
    "moshi",
    "moshi-adapters",
    "moshi-kotlin",
    "moshi-kotlin-codegen",
    "moshi-geojson",
]
moshipack = [
    "moshipack",
    "moshipack-retrofit",
]
retrofit = [
    "retrofit",
    "retrofit-adapter-guava",
    "retrofit-adapter-java8",
    "retrofit-adapter-rxjava2",
    "retrofit-adapter-rxjava3",
    "retrofit-adapter-scala",
    "retrofit-converter-gson",
    "retrofit-converter-guava",
    "retrofit-converter-jackson",
    "retrofit-converter-java8",
    "retrofit-converter-jaxb",
    "retrofit-mock",
    "retrofit-converter-moshi",
    "retrofit-converter-protobuf",
    "retrofit-converter-scalars",
    "retrofit-converter-simplexml",
    "retrofit-converter-wire",
    "retrofit2-kotlinx-serialization-converter",
]
security = [
    "tink",
]
utils = [
    "easydeviceinfo",
]
