#### Gradle Library Catalog ####
# https://docs.gradle.org/current/userguide/platforms.html
[versions]
wear = "1.3.0-rc01"
wear-input = "1.2.0-alpha02"
wear-input-testing = "1.2.0-alpha02"
wear-ongoing = "1.0.0"
wear-phone-interactions = "1.1.0-alpha03"
wear-remote-interactions = "1.1.0-alpha01"

[libraries]
wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-input = { module = "androidx.wear:wear-input", version.ref = "wear-input" }
wear-input-testing = { module = "androidx.wear:wear-input-testing", version.ref = "wear-input-testing" }
wear-ongoing = { module = "androidx.wear:wear-ongoing", version.ref = "wear-ongoing" }
wear-phone-interactions = { module = "androidx.wear:wear-phone-interactions", version.ref = "wear-phone-interactions" }
wear-remote-interactions = { module = "androidx.wear:wear-remote-interactions", version.ref = "wear-remote-interactions" }

[bundles]
wear = [
    "wear",
    "wear-input",
    "wear-input-testing",
    "wear-ongoing",
    "wear-phone-interactions",
    "wear-remote-interactions",
]
